# config/tools.yaml

tools:
  tedx_search:
    data_path: "data/github-mauropelucchi-tedx_dataset-update_2024-details.csv"

  tedx_slug:
    data_path: "data/github-mauropelucchi-tedx_dataset-update_2024-details.csv"
    llm_config:
      provider: "ollama"
      config:
        model: "ollama/llama3.2"
        temperature: 0
    embedder_config:
      provider: "ollama"
      config:
        model: "nomic-embed-text"
        temperature: 0

  tedx_transcript:
    data_path: "data/github-mauropelucchi-tedx_dataset-update_2024-details.csv"

  duckduckgo_search:

  sdg_align:
    data_path: "data/sdg_data.csv"

  sustainability_impact:
    data_path: "data/impact_data.csv"
