# config/tools.yaml

tedx_search:
  embedder_config:
    provider: ollama
    config:
      model: "nomic-embed-text"
  data_path: "data/github-mauropelucchi-tedx_dataset-update_2024-details.csv"

tedx_slug:
  embedder_config:
    provider: ollama
    config:
      model: "nomic-embed-text"
  data_path: "data/github-mauropelucchi-tedx_dataset-update_2024-details.csv"

tedx_transcript:
  embedder_config:
    provider: ollama
    config:
      model: "nomic-embed-text"
  data_path: "data/github-mauropelucchi-tedx_dataset-update_2024-details.csv"

duckduckgo_search:
  embedder_config:
    provider: ollama
    config:
      model: "nomic-embed-text"
  data_path: "data/github-mauropelucchi-tedx_dataset-update_2024-details.csv"

sdg_align:
  embedder_config:
    provider: ollama
    config:
      model: "nomic-embed-text"
  data_path: "data/sdg_data.csv"

sustainability_impact:
  embedder_config:
    provider: ollama
    config:
      model: "nomic-embed-text"
  data_path: "data/impact_data.csv"